bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
allowed_user_id: YOUR_TELEGRAM_USER_ID
models_path: "./models/checkpoints"
lora_path: "./models/lora"
vae_path: "./models/vae"
output_path: "./output"
log_path: "./logs"
default_model: "sd1#HUGGINGFACE/LINK"
default_model_type: "sd1"
default_precision: "fp16"
use_xformers: true